### ISSUE TITLE
Slider height overlap

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/storefront#655]
**Describe the bug**
When you have more than one banner, and the second is bigger than the first, we have a overlap, like this:
![image](https://user-images.githubusercontent.com/35343551/156614108-51c90dd1-2cd8-405f-9212-f358cc8dd42a.png)

**Comment by leomp12** [comment]
In **no case will be good UX to have a slider with banners in different sizes**, so the (obvious) "fix" is actually keeping the banners with the same aspect ratio, one of them should be properly adapted in an image editor.

That said, slider height is fixed with first banners aspect ratio to prevent [CLS](https://web.dev/cls/?gclid=Cj0KCQiA64GRBhCZARIsAHOLriJ0OhQCiecXuKcG9XJ_cX2PMy8zNi3vXXcjfyRjdxiidlQyxq9UwV8aAsgmEALw_wcB) , but if you really want to use images in different sizes (and make UX worse)  this can easily be disabled with:

```css
.banner-slider {
    height: auto !important;
}
```
